### ISSUE TITLE
To-do checklist

### ISSUE THREAD

**Issue by morrolinux** [ndrewh/Raspberry-pi-fm-radio-bluetooth#1]
Hi! 
if it's still matter of interest, i wanted you to know that i just found your project, and noticed that i've already done the following in my project: 
* Don't require pairing manually at first (tested on Android, windows, Linux, Mac)
* Auto-connect (to be tested)
* Don't hard code MAC in radioStart.sh (i implemented that part in another way)
i'm not working on github but you can take a look here: https://blog.morrolinux.it/raspberry-pi-fm-radio-transmitter-stereo-a2dp-bluetooth-rds/

Regards
Morrolinux

**Comment by ndrewh** [comment]
Cool! Thanks for letting me know!

I never really cared all that much about this project myself but I'm
impressed that you were able to get pairing working properly and also debug
some pulseaudio issues.

Thanks!
