### ISSUE TITLE
Bluetooth

### ISSUE THREAD

**Issue by aareben** [ndrewh/Raspberry-pi-fm-radio-bluetooth#2]
Hey, I know this is from a really long time ago, but I was wondering if it still works. If it does, can you suggest a good Bluetooth dongle for the pi. Thanks

**Comment by ndrewh** [comment]
the bluetooth dongle I used was like 5 years old at the time, so I unfortunately don't have a recommendation that is current. probably the bluetooth that is built-in to the new raspberry pis would work. I also don't have any idea if this works anymore, I suspect there are some issues with the configuration scripts i provided being for outdated versions of software

best of luck!
